name: integration_test_app
description: "Integration test app"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

  image_pipeline:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/sample/sample.jpeg