name: build

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-desktop:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            dart_os: linux
            ext: so
            arch: x64

          - os: ubuntu-24.04-arm
            dart_os: linux
            ext: so
            arch: arm64

          - os: macos-latest
            dart_os: macos
            ext: dylib
            arch: arm64

          - os: macos-latest
            dart_os: macos
            ext: dylib
            arch: x64

          - os: windows-latest
            dart_os: windows
            ext: dll
            arch: x64
            msystem: MINGW64
            msys_prefix: mingw-w64-x86_64

    runs-on: ${{ matrix.os }}

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      # INSTALL DEPENDENCIES

      - name: 📦 Install Dependencies (Ubuntu)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake pkg-config libvips-dev

      - name: 📦 Install Dependencies (macOS)
        if: startsWith(matrix.os, 'macos')
        run: |
          if [ "${{ matrix.arch }}" == "x64" ]; then
            # install x86_64 with Rosetta
            arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            arch -x86_64 /usr/local/bin/brew install cmake pkg-config vips dylibbundler
          else
            # install arm64
            brew install cmake pkg-config vips dylibbundler
          fi

      - name: 📦 Install Dependencies (Windows via MSYS2)
        if: startsWith(matrix.os, 'windows')
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          update: true
          install: >-
            ${{ matrix.msys_prefix }}-cmake
            ${{ matrix.msys_prefix }}-pkgconf
            ${{ matrix.msys_prefix }}-libvips
            ${{ matrix.msys_prefix }}-toolchain
            zip

      # BUILD LIBRARY

      - name: 🛠️ Build Library (Ubuntu / macOS)
        if: "!startsWith(matrix.os, 'windows')"
        run: |
          mkdir build
          cd build

          # macOS x64
          if [[ "${{ matrix.os }}" == *"macos"* ]] && [ "${{ matrix.arch }}" == "x64" ]; then
            export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:/usr/local/opt/vips/lib/pkgconfig"
            export PATH="/usr/local/bin:$PATH"
            cmake ../native/io/desktop -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES="x86_64"
          else
            cmake ../native/io/desktop -DCMAKE_BUILD_TYPE=Release
          fi

          make

      - name: 🛠️ Build Library (Windows)
        if: startsWith(matrix.os, 'windows')
        shell: msys2 {0}
        run: |
          mkdir build
          cd build
          cmake ../native/io/desktop -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release
          cmake --build .

      # PACKAGE ARTIFACTS

      - name: 🏷️ Package Artifact (macOS)
        if: startsWith(matrix.os, 'macos')
        run: |
          mv build/*io_desktop_transformer*.dylib build/io_transformer-${{ matrix.dart_os }}-${{ matrix.arch }}.dylib

          # bundle libs + path resolutions
          dylibbundler -b -x build/io_transformer-${{ matrix.dart_os }}-${{ matrix.arch }}.dylib -d build -p @loader_path

          cd build
          zip -j ../io_transformer-${{ matrix.dart_os }}-${{ matrix.arch }}.zip *.dylib

      - name: 🏷️ Package Artifact (Windows)
        if: startsWith(matrix.os, 'windows')
        shell: msys2 {0}
        run: |
          DLL_PATH=$(find . -name "*io_desktop_transformer*.dll" | head -n 1)

          if [ -z "$DLL_PATH" ]; then
            find . -name "*.dll"
            exit 1
          fi

          # create a clean folder for exporting
          mkdir -p win_bundle

          # move and rename the dll inside
          mv "$DLL_PATH" win_bundle/io_transformer-${{ matrix.dart_os }}-${{ matrix.arch }}.dll

          # collect all dlls for standalone execution
          ldd win_bundle/io_transformer-${{ matrix.dart_os }}-${{ matrix.arch }}.dll | grep "mingw64" | awk '{print $3}' | xargs -I '{}' cp '{}' win_bundle/

          # zip the content of the new folder
          cd win_bundle
          zip -r ../io_transformer-${{ matrix.dart_os }}-${{ matrix.arch }}.zip *.dll

      - name: 🏷️ Package Artifact (Ubuntu)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          # rename lib
          mv build/*io_desktop_transformer*.so build/io_transformer-${{ matrix.dart_os }}-${{ matrix.arch }}.so
          cd build
          zip ../io_transformer-${{ matrix.dart_os }}-${{ matrix.arch }}.zip io_transformer-${{ matrix.dart_os }}-${{ matrix.arch }}.so

      # UPLOAD ARTIFACTS

      - name: 🚀 Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: io_transformer-${{ matrix.dart_os }}-${{ matrix.arch }}.zip

  build-web:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 📥 Checkout photon repository
        uses: actions/checkout@v4
        with:
          repository: silvia-odwyer/photon
          ref: d15af4c4ee746b316fa64ccf0c9ab9972e708aa0
          path: photon

      - name: 📦 Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: 🛠️ Build photon WASM
        working-directory: ./photon/crate
        run: wasm-pack build --target web --release

      - name: 🏷️ Package web artifact
        run: |
          mkdir web_transformer_staging

          cp native/web/transformer.js web_transformer_staging/
          cp native/web/transformer_worker.js web_transformer_staging/

          cp photon/crate/pkg/photon_rs.js web_transformer_staging/
          cp photon/crate/pkg/photon_rs_bg.wasm web_transformer_staging/

          cd web_transformer_staging
          zip -r ../web_transformer.zip ./*

      - name: Upload artifact to Action
        uses: actions/upload-artifact@v4
        with:
          name: web_transformer
          path: web_transformer.zip

      - name: 🚀 Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: web_transformer.zip
