name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
  workflow_run:
    workflows: ["build"]
    types:
      - completed

jobs:
  test:
    # Only if build succeeds or non build workflow
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🛠️ Install desktop system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake pkg-config libvips-dev

      - name: 🎯 Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: 📦 Install Dart dependencies
        run: dart pub get

      - name: 📥 Download Assets
        run: dart run tool/download_assets.dart

      - name: 🧬 Generate Mobile Test Bindings
        run: dart run tool/generate_mob_test_bindings.dart

      - name: 🧪 Run IO Tests
        run: dart test --coverage=coverage_native

      - name: 🌐 Run WEB Tests
        run: dart test -p chrome --coverage=coverage_web

      - name: 🔄 Format & Merge Coverage
        run: |
          dart pub global activate coverage
          
          dart pub global run coverage:format_coverage \
            --lcov --in=coverage_native --out=coverage/native.lcov \
            --packages=.dart_tool/package_config.json --report-on=lib
            
          dart pub global run coverage:format_coverage \
            --lcov --in=coverage_web --out=coverage/web.lcov \
            --packages=.dart_tool/package_config.json --report-on=lib

      - name: ⬆ Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: coverage/
          fail_ci_if_error: true